gsap.fromTo("h1", { color: "green", x: -500 }, { duration: 4, fontFamily: "fantasy", marginTop: "30", fontSize: "3em", x: 30, ease: "bounce", color: "red" })
gsap.fromTo("body", { backgroundColor: "grey" }, { repeat: -1, duration: 5, css: { backgroundImage: 'url(img/bowling_pins.svg)', backgroundRepeat: "no-repeat", backgroundSize: "contain" }, ease: "bounce" }, 3)
gsap.fromTo("#path909", { x: -500 }, { x: 100 })
gsap.fromTo("#path1534", { x: -500 }, { x: 100 })
gsap.fromTo("#h", { y: -500 }, { repeat: -1, duration: 4, y: 0, ease: "elastic" }, 5)
gsap.fromTo("#ap", { y: -500 }, { repeat: -1, duration: 5, y: 0, ease: "elastic" }, 6)
gsap.fromTo("#py", { y: -700 }, { repeat: -1, duration: 5, y: 0, ease: "elastic" }, 7)
gsap.to("h1", { color: "black", backgroundColor: "grey", opacity: "0.9" }, 5)
gsap.fromTo("#b", { y: 700 }, { duration: 5, y: 0, ease: "elastic" }, 7)
gsap.fromTo("#irth", { y: 700 }, { duration: 5, y: 0, ease: "elastic" }, 7)
gsap.fromTo("#day", { fill: "blue", y: 700 }, { duration: 5, y: 0, ease: "elastic", fill: "red" }, 7)
gsap.fromTo("#dot", { y: 500 }, { duration: 5, y: 0, ease: "elastic" }, 7)
gsap.to("body", { backgroundColor: "black" }, 7)
gsap.to("#day", { fill: "green", repeat: "-1" }, 10)